  def test_featured(self):
    self.driver.get("http://mys01.fit.vutbr.cz:8014/index.php?route=account/register")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.ID, "input-firstname").click()
    self.driver.find_element(By.ID, "input-firstname").send_keys("aaaa")
    self.driver.find_element(By.ID, "input-lastname").click()
    self.driver.find_element(By.ID, "input-lastname").send_keys("aaaa")
    self.driver.find_element(By.ID, "input-email").click()
    self.driver.find_element(By.ID, "input-email").send_keys("aa@gmail.com")
    self.driver.find_element(By.ID, "input-telephone").send_keys("123456789")
    self.driver.find_element(By.ID, "input-address-1").click()
    self.driver.find_element(By.ID, "input-address-1").send_keys("aaaaa")
    self.driver.find_element(By.ID, "input-city").click()
    self.driver.find_element(By.ID, "input-city").send_keys("aaaaa")
    self.driver.find_element(By.ID, "input-postcode").click()
    self.driver.find_element(By.ID, "input-postcode").send_keys("58601")
    self.driver.find_element(By.ID, "input-country").click()
    dropdown = self.driver.find_element(By.ID, "input-country")
    dropdown.find_element(By.XPATH, "//option[. = 'Swaziland']").click()
    self.driver.find_element(By.ID, "input-country").click()
    self.driver.find_element(By.ID, "input-zone").click()
    dropdown = self.driver.find_element(By.ID, "input-zone")
    dropdown.find_element(By.XPATH, "//option[. = 'Manzini']").click()
    self.driver.find_element(By.ID, "input-zone").click()
    self.driver.find_element(By.ID, "input-password").click()
    self.driver.find_element(By.ID, "input-password").send_keys("12345")
    self.driver.find_element(By.ID, "input-confirm").click()
    self.driver.find_element(By.ID, "input-confirm").send_keys("12345")
    self.driver.find_element(By.NAME, "agree").click()
  
